USE Planilla
GO

CREATE TABLE dbo.CuentasPlanillas(
CORRELATIVO		INT IDENTITY,
CUENTA          VARCHAR(100),
NOMBRE_CLIENTE	VARCHAR(MAX),
DPI             VARCHAR(50),
ID				INT,
FECHA_CARGA		DATE
);

CREATE INDEX CP_idx_001 on CuentasPlanillas (DPI);
CREATE INDEX CP_idx_002 on CuentasPlanillas (CUENTA);


CREATE TABLE dbo.TransaccionesEquivalentes(
ID INT IDENTITY,
TRANSACCION VARCHAR(500),
EQUIVALENTE VARCHAR(100)
);

CREATE INDEX TE_idx_001 on TransaccionesEquivalentes (TRANSACCION);
CREATE INDEX TE_idx_002 on TransaccionesEquivalentes (EQUIVALENTE);

CREATE TABLE dbo.Transacciones(
ID INT IDENTITY,
DOCUMENTO VARCHAR(100),
NUM_DOCUMENTO VARCHAR(100),
MONTO FLOAT,
DESCRIPCION VARCHAR(500),
FECHA_CARGA DATE
);

CREATE INDEX T_idx_001 on Transacciones (DOCUMENTO);
CREATE INDEX T_idx_002 on Transacciones (DESCRIPCION);
CREATE INDEX T_idx_003 on Transacciones (NUM_DOCUMENTO);

CREATE TABLE dbo.ClientesActivosApp(
ID INT IDENTITY,
DOCUMENTO VARCHAR(100),
FECHA_CARGA DATE
);

CREATE INDEX CAA_idx_001 on ClientesActivosApp (DOCUMENTO);

CREATE TABLE dbo.ClientesActivosYolo(
ID INT IDENTITY,
DOCUMENTO VARCHAR(100),
FECHA_CARGA DATE
);

CREATE INDEX CAY_idx_001 on ClientesActivosYolo (DOCUMENTO);

CREATE TABLE dbo.ClientesActivosBl(
ID INT IDENTITY,
DOCUMENTO VARCHAR(100),
FECHA_CARGA DATE
);

CREATE INDEX CAB_idx_001 on ClientesActivosBl (DOCUMENTO);

CREATE TABLE dbo.Planilla(
ID INT IDENTITY,
NO_PLANILLA INT,
NOMBRE_PLANILLA VARCHAR(500),
FECHA_CARGA DATE
);

CREATE INDEX P_idx_001 on Planilla (NO_PLANILLA);



