CREATE PROCEDURE dbo.ELIMINARDUPLICADOS

AS

-- BUSCAMOS DUPLICADOS
 WITH C AS
 (
  SELECT DPI,ID,
  ROW_NUMBER() OVER (PARTITION BY 
                    DPI,ID
                    ORDER BY ID) AS DUPLICADO
  FROM dbo.CuentasPlanillas
  WHERE CONVERT(VARCHAR,FECHA_CARGA,105) = CONVERT(VARCHAR,GETDATE(),105)
 )
DELETE FROM C 
 WHERE DUPLICADO > 1;


 