USE Planilla
GO

CREATE PROCEDURE dbo.EditarPlanilla

@P_ID					INT,
@P_NO_PLANILLA			INT,
@NOMBRE_PLANILLA		VARCHAR(500)


AS

UPDATE	dbo.Planilla
SET		NO_PLANILLA=@P_NO_PLANILLA,
		NOMBRE_PLANILLA=@NOMBRE_PLANILLA
WHERE	ID=@P_ID